"""Replay buffers for MBPO.

Two separate FIFO buffers:
- ``ReplayBuffer`` for real environment transitions.
- ``ModelBuffer`` for imagined transitions generated by the dynamics ensemble.

A ``sample_mixed`` helper combines both for the MBPO mixed-batch update.
"""

from __future__ import annotations

from collections import deque
from typing import Any

import numpy as np
import torch


class ReplayBuffer:
    """Fixed-capacity FIFO buffer for (obs, action, reward, next_obs, done) transitions.

    All data is stored as float32.

    Parameters
    ----------
    capacity:
        Maximum number of transitions to keep.
    """

    def __init__(self, capacity: int) -> None:
        self._buffer: deque[
            tuple[np.ndarray, np.ndarray, float, np.ndarray, bool]
        ] = deque(maxlen=capacity)

    def push(
        self,
        obs: Any,
        action: Any,
        reward: float,
        next_obs: Any,
        done: bool,
    ) -> None:
        """Push a single transition."""
        self._buffer.append((
            np.asarray(obs, dtype=np.float32),
            np.asarray(action, dtype=np.float32),
            float(reward),
            np.asarray(next_obs, dtype=np.float32),
            bool(done),
        ))

    def sample(
        self, batch_size: int
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """Sample a random batch without replacement.

        Returns
        -------
        tuple of five tensors: obs, act, rew, next_obs, done — all float32.
        """
        indices = np.random.choice(len(self._buffer), size=batch_size, replace=False)
        states, actions, rewards, next_states, dones = zip(
            *(self._buffer[i] for i in indices)
        )
        return (
            torch.tensor(np.array(states), dtype=torch.float32),
            torch.tensor(np.array(actions), dtype=torch.float32),
            torch.tensor(np.array(rewards), dtype=torch.float32),
            torch.tensor(np.array(next_states), dtype=torch.float32),
            torch.tensor(np.array(dones), dtype=torch.float32),
        )

    def __len__(self) -> int:
        return len(self._buffer)


class ModelBuffer(ReplayBuffer):
    """Buffer for model-generated (imagined) transitions.

    Semantically identical to ``ReplayBuffer`` but kept as a separate class
    so that the agent can distinguish the two buffers explicitly and to
    support independent capacity settings.
    """


def sample_mixed(
    env_buffer: ReplayBuffer,
    model_buffer: ModelBuffer,
    batch_size: int,
    real_ratio: float,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """Draw a mixed batch from real and imagined transitions.

    Parameters
    ----------
    env_buffer:
        Buffer of real environment transitions.
    model_buffer:
        Buffer of model-generated transitions.
    batch_size:
        Total number of transitions to return.
    real_ratio:
        Fraction of real transitions in the batch (in [0, 1]).

    Returns
    -------
    tuple of five tensors: obs, act, rew, next_obs, done — all float32, on CPU.

    Notes
    -----
    If one buffer is empty, the entire batch is drawn from the other.
    """
    real_count = int(round(real_ratio * batch_size))
    model_count = batch_size - real_count

    env_empty = len(env_buffer) == 0
    model_empty = len(model_buffer) == 0

    if env_empty and model_empty:
        raise RuntimeError("Both env_buffer and model_buffer are empty.")

    if env_empty:
        # Fall back to all-model
        return model_buffer.sample(batch_size)

    if model_empty:
        # Fall back to all-env
        return env_buffer.sample(batch_size)

    # Clamp to available sizes
    real_count = min(real_count, len(env_buffer))
    model_count = min(model_count, len(model_buffer))

    if real_count == 0 and model_count == 0:
        return env_buffer.sample(batch_size)

    # Compensate if one side was clamped
    if real_count == 0:
        model_count = batch_size
    elif model_count == 0:
        real_count = batch_size

    tensors: list[tuple[torch.Tensor, ...]] = []
    if real_count > 0:
        tensors.append(env_buffer.sample(real_count))
    if model_count > 0:
        tensors.append(model_buffer.sample(model_count))

    return tuple(  # type: ignore[return-value]
        torch.cat([t[i] for t in tensors], dim=0) for i in range(5)
    )
